#docker-compose version
version: '3'

#list of containers
services:

  #------------------------------------#
  #               NGINX                #
  #------------------------------------#
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy

  #------------------------------------#
  #              MARIADB               #
  #------------------------------------#
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: "mariadb-admin ping -u${MARIADB_USER} -p${MARIADB_PASSWORD}"
      retries: 10
      interval: 2s

  #------------------------------------#
  #              WORDPRESS             #
  #------------------------------------#
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: "file wp-config.php"
      retries: 10
      interval: 5s
    restart: always

#volumes
volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/wordpress
      o: bind

#network configuration
networks:
  inception:
    driver: bridge
